#!/bin/bash

# Define the list of files to be deleted
FILES=(
"Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset"
"Content/Characters/Mannequin_UE4/Materials/Layers/ML_Latex_Black.uasset"
"Content/Characters/Mannequin_UE4/Materials/Layers/ML_ShinyPlastic_Beige.uasset"
"Content/Characters/Mannequin_UE4/Materials/Layers/ML_ShinyPlastic_Beige_Logo.uasset"
"Content/Characters/Mannequin_UE4/Materials/Layers/ML_SoftMetal.uasset"
"Content/Characters/Mannequin_UE4/Materials/M_MannequinUE4_Body.uasset"
"Content/Characters/Mannequin_UE4/Materials/M_MannequinUE4_ChestLogo.uasset"
"Content/Characters/Mannequin_UE4/Meshes/SK_Mannequin.uasset"
"Content/Characters/Mannequin_UE4/Meshes/SK_Mannequin_PhysicsAsset.uasset"
"Content/Characters/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_ML_Aluminum01.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_ML_Aluminum01_N.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_ML_Rubber_Blue_01_D.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_ML_Rubber_Blue_01_N.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_UE4_Mannequin_MAT_MASKA.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_UE4_Mannequin__normals.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_UELogo_Mask.uasset"
"Content/Characters/Mannequin_UE4/Textures/T_UELogo_N_TGA.uasset"
"Content/Characters/Mannequins/Animations/ABP_Manny.uasset"
"Content/Characters/Mannequins/Animations/ABP_Quinn.uasset"
"Content/Characters/Mannequins/Animations/Quinn/MF_Walk_Fwd.uasset"
"Content/Characters/Mannequins/Materials/Functions/CA_Mannequin.uasset"
"Content/Characters/Mannequins/Materials/Functions/ChromaticCurve.uasset"
"Content/Characters/Mannequins/Materials/Functions/MF_Diffraction.uasset"
"Content/Characters/Mannequins/Materials/Functions/MF_logo3layers.uasset"
"Content/Characters/Mannequins/Materials/Functions/ML_BaseColorFallOff.uasset"
"Content/Characters/Mannequins/Materials/Instances/Manny/MI_Manny_01.uasset"
"Content/Characters/Mannequins/Materials/Instances/Manny/MI_Manny_02.uasset"
"Content/Characters/Mannequins/Materials/Instances/Quinn/MI_Quinn_01.uasset"
"Content/Characters/Mannequins/Materials/Instances/Quinn/MI_Quinn_02.uasset"
"Content/Characters/Mannequins/Materials/M_Mannequin.uasset"
"Content/Characters/Mannequins/Meshes/Mannequin_LODSettings.uasset"
"Content/Characters/Mannequins/Meshes/SKM_Manny.uasset"
"Content/Characters/Mannequins/Meshes/SKM_Quinn.uasset"
"Content/Characters/Mannequins/Rigs/ABP_Manny_PostProcess.uasset"
"Content/Characters/Mannequins/Rigs/ABP_Quinn_PostProcess.uasset"
"Content/Characters/Mannequins/Rigs/Poses/Manny/Manny_clavicle_l_anim.uasset"
"Content/Characters/Mannequins/Rigs/Poses/Manny/Manny_foot_r_anim.uasset"
"Content/Characters/Mannequins/Rigs/RTG_Mannequin.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_ASAOPMASK_MSK.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_BN.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_CCRCCPlastic_MSK.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_D.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_MSR_MSK.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_N.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_01_Tan.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_ASAOPMASK_MSK.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_BN.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_CCRCCPlastic_MSK.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_D.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_MSR_MSK.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_N.uasset"
"Content/Characters/Mannequins/Textures/Manny/T_Manny_02_Tan.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01ID_BN.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01ID_D.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01ID_MSR_MSK.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01ID_N.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01ID_Tan.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01_ASAOMASK_MSK.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_01_CCRCCPlastic_MSK.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02ID_BN.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02ID_D.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02ID_MSR_MSK.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02ID_N.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02ID_Tan.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02_ASAOMASK_MSK.uasset"
"Content/Characters/Mannequins/Textures/Quinn/T_Quinn_02_CCRCCPlastic_MSK.uasset"
"Content/Characters/Mannequins/Textures/Shared/T_UE_Logo_M.uasset"
"Content/LevelPrototyping/Materials/MF_ProcGrid.uasset"
"Content/LevelPrototyping/Materials/MI_PrototypeGrid_Gray.uasset"
"Content/LevelPrototyping/Materials/MI_PrototypeGrid_Gray_02.uasset"
"Content/LevelPrototyping/Materials/MI_PrototypeGrid_TopDark.uasset"
"Content/LevelPrototyping/Materials/MI_Solid_Blue.uasset"
"Content/LevelPrototyping/Materials/M_PrototypeGrid.uasset"
"Content/LevelPrototyping/Materials/M_Solid.uasset"
"Content/LevelPrototyping/Meshes/SM_ChamferCube.uasset"
"Content/LevelPrototyping/Meshes/SM_Cube.uasset"
"Content/LevelPrototyping/Meshes/SM_Cylinder.uasset"
"Content/LevelPrototyping/Meshes/SM_QuarterCylinder.uasset"
"Content/LevelPrototyping/Meshes/SM_Ramp.uasset"
"Content/LevelPrototyping/Textures/T_GridChecker_A.uasset"
)

# Loop through the list and delete each file
for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "Deleted $file"
    else
        echo "File not found: $file"
    fi
done

echo "All specified files have been deleted."