AWSTemplateFormatVersion: '2010-09-09'
Description: BatsToi Server GameLift Resources
Parameters:
  BuildId:
    Type: String
    Description: The build version identifier
  BackendStackName:
    Type: String
    Description: The name of the backend stack
    Default: batstoi-serverless
  SecondaryLocation:
    Type: String
    Description: The region identifier for the secondary location for the Fleet
    Default: us-east-1
Resources:
  # Role for the instances (to access CloudWatch)
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - gamelift.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
  Queue:
    Type: AWS::GameLift::GameSessionQueue
    Properties:
      Name: BatsToiGameSessionQueue
      TimeoutInSeconds: 50
      Destinations:
        - DestinationArn: !Join
            - ''
            - - 'arn:aws:gamelift:'
              - !Ref AWS::Region
              - '::alias/'
              - !Ref Alias

      PlayerLatencyPolicies:
        - MaximumIndividualPlayerLatencyMilliseconds: 80
          PolicyDurationSeconds: 3
        - MaximumIndividualPlayerLatencyMilliseconds: 1000
  MatchmakingRuleSet:
    Type: AWS::GameLift::MatchmakingRuleSet
    Properties:
      Name: BatsToiGameLiftRuleSetLinux
      RuleSetBody: !Sub |
        {
            "name": "simplerule",
            "ruleLanguageVersion": "1.0",
            "playerAttributes": [{
                "name": "skill",
                "type": "number",
                "default": 10
            }],
            "teams": [{
                "name": "versus",
                "maxPlayers": 2,
                "minPlayers": 1
            }],
            "rules": [{
                "name": "FairSkill",
                "description": "The average skill of players is within 10 points from the average skill of all players in the match",
                "type": "distance",
                // get skill value for each player
                "measurements": [ "teams[versus].players.attributes[skill]" ],
                // get skill values for all players and average to produce an overall average
                "referenceValue": "avg(teams[versus].players.attributes[skill])",
                "maxDistance": 10
            },{
              "name": "FastConnection",
              "description": "Prefer matches with fast player connections first",
              "type": "latency",
              "maxLatency": 80
            }],
            "expansions": [{
                  "target": "rules[FastConnection].maxLatency",
                  "steps": [{
                      "waitTimeSeconds": 5,
                      "value": 1000
                }]
            }]
        }
  MatchMakingConfiguration:
    Type: AWS::GameLift::MatchmakingConfiguration
    Properties:
      Name: BatsToiGameConfiguration
      AcceptanceRequired: false
      AdditionalPlayerCount: 0
      RequestTimeoutSeconds: 250
      BackfillMode: AUTOMATIC
      Description: A basic sns configuration for BatsToi
      GameProperties:
        - Key: gamemode
          Value: classic
      GameSessionQueueArns:
        - !GetAtt Queue.Arn
      RuleSetName: !Ref MatchmakingRuleSet
      NotificationTarget: !ImportValue
        Fn::Sub: ${BackendStackName}-MatchmakingEventsSNSTopic
  Fleet:
    Type: AWS::GameLift::Fleet
    Properties:
      Name: BatsToiFleet
      Description: BatsToi Fleet
      Locations:
        - Location: !Ref AWS::Region
          LocationCapacity:
            DesiredEC2Instances: 1
            MaxSize: 4
            MinSize: 1
        - Location: !Ref SecondaryLocation
          LocationCapacity:
            DesiredEC2Instances: 1
            MaxSize: 1
            MinSize: 1
      BuildId: !Ref BuildId
      RuntimeConfiguration:
        GameSessionActivationTimeoutSeconds: 300
        ServerProcesses:
          - ConcurrentExecutions: 1
            LaunchPath: /local/game/BatsToiSupreme_RealServer.sh
            Parameters: 'LV_LobbyServer -HOSTTYPE=CLOUD -epicapp=DedicatedServerDev -AbsLog=/local/game/logs/game-server-7777.log -Port=7777'
          - ConcurrentExecutions: 1
            LaunchPath: /local/game/BatsToiSupreme_RealServer.sh
            Parameters: 'LV_LobbyServer -HOSTTYPE=CLOUD -epicapp=DedicatedServerDev -AbsLog=/local/game/logs/game-server-7778.log -Port=7778'
          - ConcurrentExecutions: 1
            LaunchPath: /local/game/BatsToiSupreme_RealServer.sh
            Parameters: 'LV_LobbyServer -HOSTTYPE=CLOUD -epicapp=DedicatedServerDev -AbsLog=/local/game/logs/game-server-7779.log -Port=7779'
      EC2InstanceType: m5.large
      FleetType: SPOT
      NewGameSessionProtectionPolicy: NoProtection
      EC2InboundPermissions:
        - FromPort: 7777
          ToPort: 8777
          IpRange: 0.0.0.0/0
          Protocol: UDP
      ScalingPolicies:
        - Name: BatsToiFleetScalingPolicy
          MetricName: PercentAvailableGameSessions
          PolicyType: TargetBased
          TargetConfiguration:
            TargetValue: 50
      CertificateConfiguration:
        CertificateType: GENERATED
      InstanceRoleARN: !GetAtt InstanceRole.Arn
      InstanceRoleCredentialsProvider: SHARED_CREDENTIAL_FILE
  Alias:
    Type: AWS::GameLift::Alias
    Properties:
      Name: BatsToiGameServerAlias
      Description: An alias routing traffic to the fleet
      RoutingStrategy:
        Type: SIMPLE
        FleetId: !Ref Fleet
Outputs:
  FleetID:
    Description: The ID of the created GameLift Fleet
    Value: !Ref Fleet
    Export:
      Name: !Sub ${AWS::StackName}-FleetID